baseurl: "" # Leave empty if using username.github.io
url: "https://jaydenskelly.me" # Update with your GitHub username

google_analytics: G-5RC1QGNTQZ

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - index.md
  - about.md
  - research-interests.md
  - projects.md
  - fieldwork-photos.md
  - contact.md
  #- news.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  
# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
