title: Jayden Skelly
description: Montana State University
baseurl: "" # Leave empty if using username.github.io
url: "https://yourusername.github.io" # Update with your GitHub username

# Build settings
markdown: kramdown
theme: minima

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
