title: Jayden Skelly
description: Montana State University
show_downloads: true
#google_analytics: UA-98690382-1
permalink: /:categories/:year-:month-:day-:title.html
pages_list:
  Home: '/index'
  about: '/about'
plugins:
  - jekyll-feed
github: [metadata]
