baseurl: "" # Leave empty if using username.github.io
url: "https://github.com/jskelly1/jskelly1.github.io" # Update with your GitHub username

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - index.md
  - about.md
  - research-interests.md
  - projects.md
  - fieldwork-photos.md
  - contact.md
  - news.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
